#!/usr/bin/env bash

if [[ -s "/root/.rvm/environments/ruby-1.9.3-p125@global" ]]
then
  source "/root/.rvm/environments/ruby-1.9.3-p125@global"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/root/.rvm/environments/ruby-1.9.3-p125@global'" >&2
  exit 1
fi
  